### ISSUE TITLE
Empty database on Linux

### ISSUE THREAD

**Issue by ArcticSnow** [letmaik/lensfunpy#15] opened 2018-04-30 15:44 UTC
Hi, 
Using linux Mint, I followed your installation protocol with apt-get for lensfun, and then install the lensfunpy library with pip. The python library loads just fine but its database is empty when querying for a camera such as the one in the Readme example. 

This is for instance my input and output in ipython:

```python
import lensfunpy
 
cam_maker = 'NIKON CORPORATION'
cam_model = 'NIKON D3S'
lens_maker = 'Nikon'
lens_model = 'Nikkor 28mm f/2.8D AF'
   
db = lensfunpy.Database()
cam = db.find_cameras(cam_maker, cam_model)[0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3cb54c3ab96e>", line 9, in <module>
    cam = db.find_cameras(cam_maker, cam_model)[0]
IndexError: list index out of range
```

Any idea where should I look to solve the problem?
Thanks

**Comment by letmaik** [comment] 2018-04-30 17:41
I could reproduce the problem in Ubuntu. Indeed the database is empty. Let me see where the problem is.

**Comment by letmaik** [comment] 2018-04-30 19:00
Actually, this only seems to happen with the wheels. Doing a source compile using `pip install lensfunpy --no-binary lensfunpy` solves it for me. 
Given that the Linux wheels were missing bundled db files this would be fixed by the next lensfunpy version anyway for the standard wheel installation scenario (`pip install lensfunpy`). And building from source doesn't have this problem, so that is fine as it is.

**Comment by letmaik** [comment] 2018-05-01 17:27
I just released a new alpha version, you can try it out with `pip install lensfunpy==1.7.0a2`. Let me know if it works, then we can close this issue.

**Comment by ArcticSnow** [comment] 2018-05-02 11:50
Super, it works great with your latest version. Thanks so much for your very quick fix!

**Closed** 2018-05-02 11:51 UTC
Labels: bug

**Comment by CapPow** [comment] 2019-07-05 21:18
For reference I encountered a similar issue on Windows 10 where only the lens data was not discovered. Using the same `pip install lensfunpy==1.7.0a2` suggested by @letmaik solved the issue. Thanks!

**Comment by Ir1d** [comment] 2019-08-18 07:57
`pip install lensfunpy==1.7.0a2` solves this on Ubuntu 18.04
